/*
pleasant password server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V6SearchInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V6SearchInput{}

// V6SearchInput 
type V6SearchInput struct {
	Search *string `json:"Search,omitempty"`
}

// NewV6SearchInput instantiates a new V6SearchInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV6SearchInput() *V6SearchInput {
	this := V6SearchInput{}
	return &this
}

// NewV6SearchInputWithDefaults instantiates a new V6SearchInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV6SearchInputWithDefaults() *V6SearchInput {
	this := V6SearchInput{}
	return &this
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *V6SearchInput) GetSearch() string {
	if o == nil || IsNil(o.Search) {
		var ret string
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6SearchInput) GetSearchOk() (*string, bool) {
	if o == nil || IsNil(o.Search) {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *V6SearchInput) HasSearch() bool {
	if o != nil && !IsNil(o.Search) {
		return true
	}

	return false
}

// SetSearch gets a reference to the given string and assigns it to the Search field.
func (o *V6SearchInput) SetSearch(v string) {
	o.Search = &v
}

func (o V6SearchInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V6SearchInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Search) {
		toSerialize["Search"] = o.Search
	}
	return toSerialize, nil
}

type NullableV6SearchInput struct {
	value *V6SearchInput
	isSet bool
}

func (v NullableV6SearchInput) Get() *V6SearchInput {
	return v.value
}

func (v *NullableV6SearchInput) Set(val *V6SearchInput) {
	v.value = val
	v.isSet = true
}

func (v NullableV6SearchInput) IsSet() bool {
	return v.isSet
}

func (v *NullableV6SearchInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV6SearchInput(val *V6SearchInput) *NullableV6SearchInput {
	return &NullableV6SearchInput{value: val, isSet: true}
}

func (v NullableV6SearchInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV6SearchInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


