/*
pleasant password server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V6CredentialGroupInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V6CredentialGroupInput{}

// V6CredentialGroupInput 
type V6CredentialGroupInput struct {
	// 
	CustomUserFields map[string]interface{} `json:"CustomUserFields,omitempty"`
	Tags []V6TagResult `json:"Tags,omitempty"`
	Id *string `json:"Id,omitempty"`
	Name *string `json:"Name,omitempty"`
	ParentId *string `json:"ParentId,omitempty"`
	Notes *string `json:"Notes,omitempty"`
	Expires *string `json:"Expires,omitempty"`
}

// NewV6CredentialGroupInput instantiates a new V6CredentialGroupInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV6CredentialGroupInput() *V6CredentialGroupInput {
	this := V6CredentialGroupInput{}
	return &this
}

// NewV6CredentialGroupInputWithDefaults instantiates a new V6CredentialGroupInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV6CredentialGroupInputWithDefaults() *V6CredentialGroupInput {
	this := V6CredentialGroupInput{}
	return &this
}

// GetCustomUserFields returns the CustomUserFields field value if set, zero value otherwise.
func (o *V6CredentialGroupInput) GetCustomUserFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomUserFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomUserFields
}

// GetCustomUserFieldsOk returns a tuple with the CustomUserFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialGroupInput) GetCustomUserFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomUserFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomUserFields, true
}

// HasCustomUserFields returns a boolean if a field has been set.
func (o *V6CredentialGroupInput) HasCustomUserFields() bool {
	if o != nil && !IsNil(o.CustomUserFields) {
		return true
	}

	return false
}

// SetCustomUserFields gets a reference to the given map[string]interface{} and assigns it to the CustomUserFields field.
func (o *V6CredentialGroupInput) SetCustomUserFields(v map[string]interface{}) {
	o.CustomUserFields = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *V6CredentialGroupInput) GetTags() []V6TagResult {
	if o == nil || IsNil(o.Tags) {
		var ret []V6TagResult
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialGroupInput) GetTagsOk() ([]V6TagResult, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *V6CredentialGroupInput) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []V6TagResult and assigns it to the Tags field.
func (o *V6CredentialGroupInput) SetTags(v []V6TagResult) {
	o.Tags = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V6CredentialGroupInput) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialGroupInput) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V6CredentialGroupInput) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *V6CredentialGroupInput) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V6CredentialGroupInput) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialGroupInput) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V6CredentialGroupInput) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V6CredentialGroupInput) SetName(v string) {
	o.Name = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *V6CredentialGroupInput) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialGroupInput) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *V6CredentialGroupInput) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *V6CredentialGroupInput) SetParentId(v string) {
	o.ParentId = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *V6CredentialGroupInput) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialGroupInput) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *V6CredentialGroupInput) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *V6CredentialGroupInput) SetNotes(v string) {
	o.Notes = &v
}

// GetExpires returns the Expires field value if set, zero value otherwise.
func (o *V6CredentialGroupInput) GetExpires() string {
	if o == nil || IsNil(o.Expires) {
		var ret string
		return ret
	}
	return *o.Expires
}

// GetExpiresOk returns a tuple with the Expires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialGroupInput) GetExpiresOk() (*string, bool) {
	if o == nil || IsNil(o.Expires) {
		return nil, false
	}
	return o.Expires, true
}

// HasExpires returns a boolean if a field has been set.
func (o *V6CredentialGroupInput) HasExpires() bool {
	if o != nil && !IsNil(o.Expires) {
		return true
	}

	return false
}

// SetExpires gets a reference to the given string and assigns it to the Expires field.
func (o *V6CredentialGroupInput) SetExpires(v string) {
	o.Expires = &v
}

func (o V6CredentialGroupInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V6CredentialGroupInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomUserFields) {
		toSerialize["CustomUserFields"] = o.CustomUserFields
	}
	if !IsNil(o.Tags) {
		toSerialize["Tags"] = o.Tags
	}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.ParentId) {
		toSerialize["ParentId"] = o.ParentId
	}
	if !IsNil(o.Notes) {
		toSerialize["Notes"] = o.Notes
	}
	if !IsNil(o.Expires) {
		toSerialize["Expires"] = o.Expires
	}
	return toSerialize, nil
}

type NullableV6CredentialGroupInput struct {
	value *V6CredentialGroupInput
	isSet bool
}

func (v NullableV6CredentialGroupInput) Get() *V6CredentialGroupInput {
	return v.value
}

func (v *NullableV6CredentialGroupInput) Set(val *V6CredentialGroupInput) {
	v.value = val
	v.isSet = true
}

func (v NullableV6CredentialGroupInput) IsSet() bool {
	return v.isSet
}

func (v *NullableV6CredentialGroupInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV6CredentialGroupInput(val *V6CredentialGroupInput) *NullableV6CredentialGroupInput {
	return &NullableV6CredentialGroupInput{value: val, isSet: true}
}

func (v NullableV6CredentialGroupInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV6CredentialGroupInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


