/*
pleasant password server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V6CredentialInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V6CredentialInput{}

// V6CredentialInput 
type V6CredentialInput struct {
	// 
	CustomUserFields map[string]interface{} `json:"CustomUserFields,omitempty"`
	Tags []V6TagResult `json:"Tags,omitempty"`
	Name *string `json:"Name,omitempty"`
	Username *string `json:"Username,omitempty"`
	Password *string `json:"Password,omitempty"`
	Url *string `json:"Url,omitempty"`
	Notes *string `json:"Notes,omitempty"`
	GroupId *string `json:"GroupId,omitempty"`
	Expires *string `json:"Expires,omitempty"`
}

// NewV6CredentialInput instantiates a new V6CredentialInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV6CredentialInput() *V6CredentialInput {
	this := V6CredentialInput{}
	return &this
}

// NewV6CredentialInputWithDefaults instantiates a new V6CredentialInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV6CredentialInputWithDefaults() *V6CredentialInput {
	this := V6CredentialInput{}
	return &this
}

// GetCustomUserFields returns the CustomUserFields field value if set, zero value otherwise.
func (o *V6CredentialInput) GetCustomUserFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomUserFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomUserFields
}

// GetCustomUserFieldsOk returns a tuple with the CustomUserFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialInput) GetCustomUserFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomUserFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomUserFields, true
}

// HasCustomUserFields returns a boolean if a field has been set.
func (o *V6CredentialInput) HasCustomUserFields() bool {
	if o != nil && !IsNil(o.CustomUserFields) {
		return true
	}

	return false
}

// SetCustomUserFields gets a reference to the given map[string]interface{} and assigns it to the CustomUserFields field.
func (o *V6CredentialInput) SetCustomUserFields(v map[string]interface{}) {
	o.CustomUserFields = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *V6CredentialInput) GetTags() []V6TagResult {
	if o == nil || IsNil(o.Tags) {
		var ret []V6TagResult
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialInput) GetTagsOk() ([]V6TagResult, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *V6CredentialInput) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []V6TagResult and assigns it to the Tags field.
func (o *V6CredentialInput) SetTags(v []V6TagResult) {
	o.Tags = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V6CredentialInput) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialInput) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V6CredentialInput) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V6CredentialInput) SetName(v string) {
	o.Name = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *V6CredentialInput) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialInput) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *V6CredentialInput) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *V6CredentialInput) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *V6CredentialInput) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialInput) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *V6CredentialInput) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *V6CredentialInput) SetPassword(v string) {
	o.Password = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *V6CredentialInput) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialInput) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *V6CredentialInput) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *V6CredentialInput) SetUrl(v string) {
	o.Url = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *V6CredentialInput) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialInput) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *V6CredentialInput) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *V6CredentialInput) SetNotes(v string) {
	o.Notes = &v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *V6CredentialInput) GetGroupId() string {
	if o == nil || IsNil(o.GroupId) {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialInput) GetGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.GroupId) {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *V6CredentialInput) HasGroupId() bool {
	if o != nil && !IsNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *V6CredentialInput) SetGroupId(v string) {
	o.GroupId = &v
}

// GetExpires returns the Expires field value if set, zero value otherwise.
func (o *V6CredentialInput) GetExpires() string {
	if o == nil || IsNil(o.Expires) {
		var ret string
		return ret
	}
	return *o.Expires
}

// GetExpiresOk returns a tuple with the Expires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V6CredentialInput) GetExpiresOk() (*string, bool) {
	if o == nil || IsNil(o.Expires) {
		return nil, false
	}
	return o.Expires, true
}

// HasExpires returns a boolean if a field has been set.
func (o *V6CredentialInput) HasExpires() bool {
	if o != nil && !IsNil(o.Expires) {
		return true
	}

	return false
}

// SetExpires gets a reference to the given string and assigns it to the Expires field.
func (o *V6CredentialInput) SetExpires(v string) {
	o.Expires = &v
}

func (o V6CredentialInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V6CredentialInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomUserFields) {
		toSerialize["CustomUserFields"] = o.CustomUserFields
	}
	if !IsNil(o.Tags) {
		toSerialize["Tags"] = o.Tags
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Username) {
		toSerialize["Username"] = o.Username
	}
	if !IsNil(o.Password) {
		toSerialize["Password"] = o.Password
	}
	if !IsNil(o.Url) {
		toSerialize["Url"] = o.Url
	}
	if !IsNil(o.Notes) {
		toSerialize["Notes"] = o.Notes
	}
	if !IsNil(o.GroupId) {
		toSerialize["GroupId"] = o.GroupId
	}
	if !IsNil(o.Expires) {
		toSerialize["Expires"] = o.Expires
	}
	return toSerialize, nil
}

type NullableV6CredentialInput struct {
	value *V6CredentialInput
	isSet bool
}

func (v NullableV6CredentialInput) Get() *V6CredentialInput {
	return v.value
}

func (v *NullableV6CredentialInput) Set(val *V6CredentialInput) {
	v.value = val
	v.isSet = true
}

func (v NullableV6CredentialInput) IsSet() bool {
	return v.isSet
}

func (v *NullableV6CredentialInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV6CredentialInput(val *V6CredentialInput) *NullableV6CredentialInput {
	return &NullableV6CredentialInput{value: val, isSet: true}
}

func (v NullableV6CredentialInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV6CredentialInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


